apiVersion: apps/v1
kind: Deployment
metadata:
  name: payslip-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payslip-app
  template:
    metadata:
      labels:
        app: payslip-app
    spec:
      containers:
      - name: payslip-app
        image: 135519368857.dkr.ecr.ap-southeast-4.amazonaws.com/employee-payslip:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payslip-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: payslip-app
